(() => {
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c]));
  const toast = message => { const node = document.createElement('div'); node.className = 'toast'; node.textContent = message; document.body.appendChild(node); setTimeout(() => node.remove(), 2200); };
  const image = item => item.image ? `<img src="${esc(item.image)}" alt="" style="width:44px;height:38px;object-fit:cover;border-radius:7px">` : esc(item.icon || '✦');
  const value = id => document.getElementById(id).value;
  function renderContent() {
    const table = document.getElementById('contentTable'); if (!table) return;
    const query = value('contentSearch').toLowerCase(); const status = value('contentStatusFilter'); const category = value('contentCategoryFilter');
    const items = getContents().filter(item => (!query || [item.title,item.category,item.author,item.status].join(' ').toLowerCase().includes(query)) && (!status || item.status === status) && (!category || item.category === category));
    table.innerHTML = items.map(item => `<tr><td>${image(item)}</td><td class="title-cell">${esc(item.title)}</td><td>${esc(item.category)}</td><td>${esc(item.author)}</td><td><span class="status ${esc(item.status)}">${esc(item.status)}</span></td><td>${esc(item.date || item.publishDate)}</td><td>${Number(item.views || 0).toLocaleString()}</td><td><div class="actions"><button class="icon-button" data-action="view" data-id="${item.id}">View</button><button class="icon-button" data-action="edit" data-id="${item.id}" data-testid="edit-content">Edit</button><button class="icon-button" data-action="delete" data-id="${item.id}" data-testid="delete-content">Delete</button></div></td></tr>`).join('') || '<tr><td colspan="8" class="empty">No content found.</td></tr>';
  }
  function renderCategories() {
    const list = document.getElementById('adminCategoryList'); if (!list) return;
    const query = value('categorySearch').toLowerCase();
    list.innerHTML = getCategories().filter(item => item.toLowerCase().includes(query)).map(item => `<div class="category-row"><strong>${esc(item)}</strong><div class="actions"><button class="icon-button" data-cat="edit" data-name="${esc(item)}">Edit</button><button class="icon-button" data-cat="delete" data-name="${esc(item)}">Delete</button></div></div>`).join('') || '<div class="empty">No categories found.</div>';
  }
  function renderAuthors() { const list = document.getElementById('adminAuthorList'); if (!list) return; const authors = [...new Set(getContents().map(item => item.author).filter(Boolean))].sort(); list.innerHTML = authors.map(author => `<div class="category-row"><strong>${esc(author)}</strong><span>${getContents().filter(item => item.author === author).length} articles</span></div>`).join('') || '<div class="empty">No authors found.</div>'; }
  function setupContent() {
    const category = document.getElementById('contentCategory'); const categories = getCategories(); category.innerHTML = categories.map(item => `<option>${esc(item)}</option>`).join('');
    const filter = document.getElementById('contentCategoryFilter'); filter.innerHTML = '<option value="">All categories</option>' + categories.map(item => `<option>${esc(item)}</option>`).join('');
    const existing = getContentById(new URLSearchParams(location.search).get('edit'));
    if (existing) { contentTitle.value = existing.title; contentCategory.value = existing.category; contentAuthor.value = existing.author; contentTags.value = (existing.tags || []).join(', '); contentImage.value = existing.image || ''; contentDescription.value = existing.description; contentFull.value = existing.content; contentStatus.value = existing.status; }
    document.getElementById('addContentForm').addEventListener('submit', event => {
      event.preventDefault();
      const item = { id: existing?.id || Date.now(), title: value('contentTitle').trim(), category: value('contentCategory'), author: value('contentAuthor').trim(), tags: value('contentTags').split(',').map(tag => tag.trim()).filter(Boolean), image: value('contentImage').trim(), description: value('contentDescription').trim(), content: value('contentFull').trim(), status: value('contentStatus'), date: existing?.date || new Date().toLocaleDateString('en-US', { month:'short', day:'numeric', year:'numeric' }), publishDate: existing?.publishDate || new Date().toISOString().slice(0,10), readTime: existing?.readTime || '3 min read', views: existing?.views || 0, icon: existing?.icon || '✦' };
      if (!item.title || !item.description || !item.content) { toast('Complete required fields'); return; }
      existing ? updateContent(item) : addContent(item); toast(existing ? 'Content updated' : 'Content saved'); location.href = 'admin-content.html';
    });
    ['contentSearch','contentCategoryFilter','contentStatusFilter'].forEach(id => document.getElementById(id).addEventListener('input', renderContent));
    document.getElementById('contentTable').addEventListener('click', event => { const button = event.target.closest('[data-action]'); if (!button) return; const item = getContentById(button.dataset.id); if (button.dataset.action === 'view') location.href = `article-details.html?id=${item.id}`; if (button.dataset.action === 'edit') location.href = `admin-content.html?edit=${item.id}`; if (button.dataset.action === 'delete' && confirm(`Delete “${item.title}”?`)) { deleteContent(item.id); toast('Content deleted'); renderContent(); } }); renderContent();
  }
  function setupCategories() { document.getElementById('categorySearch').addEventListener('input', renderCategories); document.getElementById('addCategoryForm').addEventListener('submit', event => { event.preventDefault(); const name = value('categoryName').trim(); if (name && !getCategories().includes(name)) { saveCategories([...getCategories(), name]); document.getElementById('categoryName').value = ''; toast('Category added'); renderCategories(); } }); document.getElementById('adminCategoryList').addEventListener('click', event => { const button = event.target.closest('[data-cat]'); if (!button) return; const name = button.dataset.name; if (button.dataset.cat === 'edit') { const next = prompt('Rename category', name)?.trim(); if (next && next !== name && !getCategories().includes(next)) { saveCategories(getCategories().map(item => item === name ? next : item)); saveContents(getContents().map(item => item.category === name ? {...item, category:next} : item)); toast('Category updated'); renderCategories(); } } else if (confirm(`Delete ${name}? Existing content moves to Uncategorized.`)) { saveCategories(getCategories().filter(item => item !== name)); saveContents(getContents().map(item => item.category === name ? {...item, category:'Uncategorized'} : item)); toast('Category deleted'); renderCategories(); } }); renderCategories(); }
  document.addEventListener('DOMContentLoaded', () => { const page = document.body.dataset.adminPage; if (page === 'content') setupContent(); if (page === 'categories') setupCategories(); if (page === 'authors') renderAuthors(); });
})();
