(() => {
  const $ = id => document.getElementById(id);
  const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
  const image = item => item.image ? `<img src="${escapeHtml(item.image)}" alt="">` : escapeHtml(item.icon || '✦');
  const toast = message => { const node = document.createElement('div'); node.className = 'toast'; node.textContent = message; document.body.appendChild(node); setTimeout(() => node.remove(), 2400); };
  let editingId = null;

  function showView(view) { document.querySelectorAll('.view').forEach(node => node.classList.toggle('active', node.id === view)); document.querySelectorAll('.side-nav button').forEach(node => node.classList.toggle('active', node.dataset.view === view)); $('pageTitle').textContent = view === 'editor' ? (editingId ? 'Edit content' : 'Add content') : view.charAt(0).toUpperCase() + view.slice(1); $('sidebar').classList.remove('open'); }
  function renderStats() { const items = getContents(); const published = items.filter(item => item.status === 'Published').length; const drafts = items.filter(item => item.status === 'Draft').length; const views = items.reduce((total, item) => total + Number(item.views || 0), 0); $('statsGrid').innerHTML = [['Total Content', items.length], ['Published', published], ['Drafts', drafts], ['Categories', getCategories().length], ['Authors', new Set(items.map(item => item.author)).size], ['Total Views', views.toLocaleString()]].map(([label, value]) => `<div class="stat-card"><small>${label}</small><strong>${value}</strong></div>`).join(''); }
  function renderDashboard() { const items = [...getContents()].sort((a,b) => new Date(b.publishDate || b.date) - new Date(a.publishDate || a.date)); $('recentTable').innerHTML = items.slice(0,5).map(item => `<tr><td class="title-cell">${escapeHtml(item.title)}</td><td><span class="status ${escapeHtml(item.status)}">${escapeHtml(item.status)}</span></td><td>${Number(item.views || 0).toLocaleString()}</td></tr>`).join('') || '<tr><td colspan="3" class="empty">No content yet.</td></tr>'; const values = [18, 35, 28, 56, 43, 68, 82]; $('barChart').innerHTML = values.map((value, index) => `<div class="bar" style="height:${value}%"><span>${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][index]}</span></div>`).join(''); $('activityList').innerHTML = items.slice(0,3).map(item => `<div class="activity"><i class="activity-dot"></i><p><strong>${escapeHtml(item.title)}</strong><br><small>${escapeHtml(item.status)} · ${Number(item.views || 0).toLocaleString()} views</small></p></div>`).join('') || '<div class="empty">No activity yet.</div>'; }
  function categoryOptions(select, includeAll = false) { const categories = getCategories(); select.innerHTML = (includeAll ? '<option value="">All categories</option>' : '') + categories.map(category => `<option>${escapeHtml(category)}</option>`).join(''); }
  function renderTable() { const query = $('searchContent').value.toLowerCase().trim(); const category = $('filterCategory').value; const status = $('filterStatus').value; let items = getContents().filter(item => (!query || [item.title,item.category,item.author,item.status].join(' ').toLowerCase().includes(query)) && (!category || item.category === category) && (!status || item.status === status)); const sort = $('sortContent').value; items.sort((a,b) => sort === 'views' ? Number(b.views || 0) - Number(a.views || 0) : sort === 'title' ? a.title.localeCompare(b.title) : new Date(b.publishDate || b.date) - new Date(a.publishDate || a.date)); $('contentTable').innerHTML = items.length ? items.map(item => `<tr><td><div class="thumb">${image(item)}</div></td><td class="title-cell">${escapeHtml(item.title)}</td><td>${escapeHtml(item.category)}</td><td>${escapeHtml(item.author)}</td><td><span class="status ${escapeHtml(item.status)}">${escapeHtml(item.status)}</span></td><td>${escapeHtml(item.date || item.publishDate || '-')}</td><td>${Number(item.views || 0).toLocaleString()}</td><td><div class="actions"><button class="icon-button" data-action="view" data-id="${item.id}" title="View">View</button><button class="icon-button" data-action="edit" data-id="${item.id}" data-testid="edit-content" title="Edit">Edit</button><button class="icon-button" data-action="delete" data-id="${item.id}" data-testid="delete-content" title="Delete">Delete</button></div></td></tr>`).join('') : '<tr><td colspan="8" class="empty">No content matches your filters.</td></tr>'; }
  function renderCategories() { const query = $('searchCategory').value.toLowerCase().trim(); $('categoryList').innerHTML = getCategories().filter(category => category.toLowerCase().includes(query)).map(category => `<div class="category-row"><strong>${escapeHtml(category)}</strong><div class="actions"><button class="icon-button" data-category-action="edit" data-category="${escapeHtml(category)}">Edit</button><button class="icon-button" data-category-action="delete" data-category="${escapeHtml(category)}">Delete</button></div></div>`).join('') || '<div class="empty">No categories found.</div>'; }
  function renderAuthors() { const authors = [...new Set(getContents().map(item => item.author).filter(Boolean))].sort(); $('authorList').innerHTML = authors.map(author => `<div class="category-row"><strong>${escapeHtml(author)}</strong><span>${getContents().filter(item => item.author === author).length} content items</span></div>`).join('') || '<div class="empty">No authors yet.</div>'; }
  function refresh() { renderStats(); renderDashboard(); categoryOptions($('filterCategory'), true); categoryOptions($('category')); renderTable(); renderCategories(); renderAuthors(); }
  function clearEditor() { editingId = null; $('editorForm').reset(); $('editId').value = ''; $('imagePreview').textContent = 'Image preview'; $('status').value = 'Draft'; }
  function fillEditor(item) { editingId = item.id; $('editId').value = item.id; $('title').value = item.title; $('category').value = item.category; $('author').value = item.author; $('tags').value = (item.tags || []).join(', '); $('status').value = item.status; $('image').value = item.image || ''; $('shortDescription').value = item.description || ''; $('fullContent').value = item.content || ''; updatePreview(); }
  function updatePreview() { $('imagePreview').innerHTML = $('image').value ? `<img src="${escapeHtml($('image').value)}" alt="Cover preview" onerror="this.parentElement.textContent='Unable to load image'">` : 'Image preview'; }
  function save(status) { const existing = editingId ? getContents().find(item => item.id === editingId) : null; const item = { id: editingId || Date.now(), title: $('title').value.trim(), category: $('category').value, author: $('author').value.trim(), tags: $('tags').value.split(',').map(tag => tag.trim()).filter(Boolean), image: $('image').value.trim(), description: $('shortDescription').value.trim(), content: $('fullContent').value.trim(), status, date: existing?.date || new Date().toLocaleDateString('en-US', { month:'short', day:'numeric', year:'numeric' }), publishDate: existing?.publishDate || new Date().toISOString().slice(0,10), readTime: existing?.readTime || '3 min read', views: existing?.views || 0, icon: existing?.icon || '✦' }; if (!item.title || !item.category || !item.author || !item.description || !item.content) { toast('Complete the required fields first'); return; } editingId ? updateContent(item) : addContent(item); toast(status === 'Published' ? 'Content published' : 'Draft saved'); showView('content'); refresh(); }
  document.addEventListener('DOMContentLoaded', () => { document.querySelectorAll('.side-nav button').forEach(button => button.addEventListener('click', () => showView(button.dataset.view))); document.querySelectorAll('[data-view-link]').forEach(button => button.addEventListener('click', () => showView(button.dataset.viewLink))); $('menuButton').addEventListener('click', () => $('sidebar').classList.toggle('open')); $('addContent').addEventListener('click', () => { clearEditor(); showView('editor'); }); $('cancelEdit').addEventListener('click', () => showView('content')); $('publishContent').addEventListener('click', () => save('Published')); $('editorForm').addEventListener('submit', event => { event.preventDefault(); save($('status').value); }); $('image').addEventListener('input', updatePreview); ['searchContent','filterCategory','filterStatus','sortContent'].forEach(id => $(id).addEventListener('input', renderTable)); $('searchCategory').addEventListener('input', renderCategories); $('contentTable').addEventListener('click', event => { const button = event.target.closest('[data-action]'); if (!button) return; const item = getContents().find(entry => entry.id === Number(button.dataset.id)); if (button.dataset.action === 'view') { window.open(`index.html#content-${item.id}`, '_blank'); } if (button.dataset.action === 'edit') { fillEditor(item); showView('editor'); } if (button.dataset.action === 'delete' && confirm(`Delete “${item.title}”?`)) { deleteContent(item.id); toast('Content deleted'); refresh(); } }); $('categoryList').addEventListener('click', event => { const button = event.target.closest('[data-category-action]'); if (!button) return; const category = button.dataset.category; if (button.dataset.categoryAction === 'edit') { const next = prompt('Rename category', category)?.trim(); if (next && next !== category && !getCategories().includes(next)) { saveCategories(getCategories().map(item => item === category ? next : item)); saveContents(getContents().map(item => item.category === category ? { ...item, category: next } : item)); toast('Category updated'); refresh(); } } else if (confirm(`Delete ${category}? Existing content will be moved to Uncategorized.`)) { saveCategories(getCategories().filter(item => item !== category)); saveContents(getContents().map(item => item.category === category ? { ...item, category: 'Uncategorized' } : item)); toast('Category deleted'); refresh(); } }); $('addCategory').addEventListener('click', () => { const name = prompt('Category name')?.trim(); if (name && !getCategories().includes(name)) { saveCategories([...getCategories(), name]); toast('Category added'); refresh(); } }); refresh(); });
  window.addEventListener('storage', refresh);
})();
