(() => {
  const icons = ['💻','📚','📈','🌱','🩺','✈️','💰'];
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const image = item => item.image ? `<img src="${esc(item.image)}" alt="${esc(item.title)}">` : `<span>${esc(item.icon || '✦')}</span>`;
  const published = () => getContents().filter(item => item.status === 'Published');
  const dateValue = item => item.publishDate || item.date || '';
  const byDate = items => [...items].sort((a,b) => new Date(dateValue(b)) - new Date(dateValue(a)));
  const card = item => `<article class="card" data-testid="article-card"><div class="media">${image(item)}</div><div class="card-body"><span class="eyebrow">${esc(item.category)}</span><h3>${esc(item.title)}</h3><p>${esc(item.description)}</p><div class="meta"><span>${esc(item.author)}</span><span>${esc(item.readTime || '3 min read')}</span></div><a class="read-more" data-testid="read-more" href="article-details.html?id=${encodeURIComponent(item.id)}">Read More →</a></div></article>`;
  const rank = (item, index) => `<article class="rank-card"><strong class="rank">0${index + 1}</strong><div><h3>${esc(item.title)}</h3><p class="muted">${esc(item.category)} · ${Number(item.views || 0).toLocaleString()} views</p><a class="read-more" data-testid="read-more" href="article-details.html?id=${encodeURIComponent(item.id)}">Read More →</a></div></article>`;
  const showToast = message => { const node = document.createElement('div'); node.className = 'toast'; node.textContent = message; document.body.appendChild(node); setTimeout(() => node.remove(), 2400); };
  window.showToast = showToast;
  function setupNav() { const toggle = document.querySelector('.mobile-toggle'); const links = document.querySelector('.nav-links'); toggle?.addEventListener('click', () => links.classList.toggle('open')); document.querySelectorAll('[data-testid="search"]').forEach(el => el.addEventListener('click', () => { window.location.href = 'search.html'; })); }
  function renderHome() { const items = byDate(published()); const featured = items[0]; const feature = document.querySelector('#featured'); if (featured && feature) feature.innerHTML = `<div class="media">${image(featured)}</div><div class="feature-body"><span class="eyebrow">FEATURED STORY</span><h2>${esc(featured.title)}</h2><p class="muted">${esc(featured.description)}</p><div class="meta"><span>${esc(featured.author)}</span><span>${esc(featured.readTime || '3 min read')}</span></div><a class="read-more" href="article-details.html?id=${featured.id}">Read the story →</a></div>`; const latest = document.querySelector('#latestGrid'); if (latest) latest.innerHTML = items.slice(0,3).map(card).join('') || '<div class="empty">No published articles yet.</div>'; const trending = document.querySelector('#trendingGrid'); if (trending) trending.innerHTML = [...items].sort((a,b) => Number(b.views||0)-Number(a.views||0)).slice(0,3).map(rank).join('') || '<div class="empty">No trending articles yet.</div>'; renderCategoryCards(); }
  function renderCategoryCards() { const target = document.querySelector('#categoryGrid'); if (!target) return; target.innerHTML = getCategories().map((category,index) => `<a class="category-card" data-testid="category-card" href="articles.html?category=${encodeURIComponent(category)}"><div class="category-icon">${icons[index % icons.length]}</div><h3>${esc(category)}</h3><p>${published().filter(item => item.category === category).length} published articles</p></a>`).join(''); }
  function renderArticles() { const target = document.querySelector('#articleGrid'); if (!target) return; const params = new URLSearchParams(location.search); const selectedCategory = params.get('category') || ''; const selectedAuthor = params.get('author') || ''; const search = document.querySelector('#articleSearch')?.value.toLowerCase().trim() || ''; const category = document.querySelector('#articleCategory')?.value || selectedCategory; const author = document.querySelector('#articleAuthor')?.value || selectedAuthor; let items = published().filter(item => (!search || [item.title,item.description,item.category,item.author,...(item.tags||[])].join(' ').toLowerCase().includes(search)) && (!category || item.category === category) && (!author || item.author === author)); const sort = document.querySelector('#articleSort')?.value || 'date'; items.sort((a,b) => sort === 'views' ? Number(b.views||0)-Number(a.views||0) : sort === 'title' ? a.title.localeCompare(b.title) : new Date(dateValue(b))-new Date(dateValue(a))); target.innerHTML = items.length ? items.map(card).join('') : '<div class="empty">No published articles match these filters.</div>'; }
  function initArticles() { const category = document.querySelector('#articleCategory'); const author = document.querySelector('#articleAuthor'); if (!category) return; const params = new URLSearchParams(location.search); category.innerHTML = '<option value="">All categories</option>' + getCategories().map(item => `<option>${esc(item)}</option>`).join(''); author.innerHTML = '<option value="">All authors</option>' + [...new Set(published().map(item => item.author))].sort().map(item => `<option>${esc(item)}</option>`).join(''); category.value = params.get('category') || ''; author.value = params.get('author') || ''; ['articleSearch','articleCategory','articleAuthor','articleSort'].forEach(id => document.getElementById(id)?.addEventListener('input', renderArticles)); renderArticles(); }
  function initTrending() { const target = document.querySelector('#rankGrid'); if (target) target.innerHTML = [...published()].sort((a,b) => Number(b.views||0)-Number(a.views||0)).map(rank).join('') || '<div class="empty">No trending content yet.</div>'; }
  function initSearch() { const form = document.querySelector('#searchForm'); const input = document.querySelector('#searchQuery'); const target = document.querySelector('#searchResults'); if (!input || !target) return; const render = () => { const term = input.value.toLowerCase().trim(); const items = published().filter(item => !term || [item.title,item.description,item.category,item.author,...(item.tags||[])].join(' ').toLowerCase().includes(term)); target.innerHTML = items.length ? items.map(item => `<div class="card"><div class="card-body"><span class="eyebrow">${esc(item.category)} · ${esc(item.author)} · ${esc(item.date || item.publishDate)}</span><h3>${esc(item.title)}</h3><p>${esc(item.description)}</p><a class="read-more" href="article-details.html?id=${item.id}">Read More →</a></div></div>`).join('') : '<div class="empty">No results found.</div>'; }; const term = new URLSearchParams(location.search).get('q'); if (term) input.value = term; form?.addEventListener('submit', event => { event.preventDefault(); history.replaceState({}, '', `search.html?q=${encodeURIComponent(input.value)}`); render(); }); input.addEventListener('input', render); render(); }
  function initDetails() { const target = document.querySelector('#articleDetail'); if (!target) return; const item = getContentById(new URLSearchParams(location.search).get('id')); if (!item || item.status !== 'Published') { target.innerHTML = '<div class="empty">This article is unavailable.</div>'; return; } const related = published().filter(entry => entry.id !== item.id && entry.category === item.category).slice(0,3); target.innerHTML = `<div class="article-main"><div class="media">${image(item)}</div><span class="eyebrow">${esc(item.category)}</span><h1>${esc(item.title)}</h1><p class="muted">By ${esc(item.author)} · ${esc(item.date || item.publishDate)} · ${esc(item.readTime || '3 min read')}</p><div class="article-actions"><button class="button" id="likeButton">♡ Like</button><button class="button secondary" id="shareButton">↗ Share</button></div><div class="article-content">${esc(item.content || item.description)}</div><div class="tags">${(item.tags||[]).map(tag => `<span class="tag">#${esc(tag)}</span>`).join('')}</div></div><aside><h2>Related Articles</h2><div class="sidebar-list">${related.map((entry,index) => rank(entry,index)).join('') || '<div class="empty">More stories coming soon.</div>'}</div></aside>`; document.querySelector('#likeButton').addEventListener('click', event => { event.currentTarget.textContent = '♥ Liked'; showToast('Added to your reading list'); }); document.querySelector('#shareButton').addEventListener('click', async () => { try { await navigator.clipboard.writeText(location.href); showToast('Article link copied'); } catch { showToast('Copy the URL from your browser'); } }); }
  function initCreate() { const form = document.querySelector('#createForm'); if (!form) return; document.querySelector('#contentCategory').innerHTML = getCategories().map(category => `<option>${esc(category)}</option>`).join(''); const save = status => { const item = { id: Date.now(), title: document.querySelector('#contentTitle').value.trim(), category: document.querySelector('#contentCategory').value, author: document.querySelector('#contentAuthor').value.trim(), tags: document.querySelector('#contentTags').value.split(',').map(tag => tag.trim()).filter(Boolean), image: document.querySelector('#contentImage').value.trim(), description: document.querySelector('#contentShortDescription').value.trim(), content: document.querySelector('#contentFullContent').value.trim(), status, date: new Date().toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}), publishDate: new Date().toISOString().slice(0,10), readTime:'3 min read', views:0, icon:'✦' }; if (!item.title || !item.category || !item.author || !item.description || !item.content) { showToast('Complete all required fields'); return; } addContent(item); showToast(status === 'Published' ? 'Article published' : 'Draft saved'); form.reset(); }; form.addEventListener('submit', event => { event.preventDefault(); save('Draft'); }); document.querySelector('#publishContent')?.addEventListener('click', () => save('Published')); }
  document.addEventListener('DOMContentLoaded', () => { setupNav(); renderHome(); renderCategoryCards(); initArticles(); initTrending(); initSearch(); initDetails(); initCreate(); });
  window.addEventListener('storage', () => { renderHome(); renderCategoryCards(); renderArticles(); initTrending(); initSearch(); });
})();
