(() => {
  const CONTENT_KEY = 'contenthub_contents_v1';
  const CATEGORY_KEY = 'contenthub_categories_v1';
  const defaultCategories = ['Technology', 'Education', 'Business', 'Lifestyle', 'Health', 'Travel', 'Finance'];
  const defaults = [
    { id: 1, title: 'The Future of Artificial Intelligence', category: 'Technology', description: 'Explore how artificial intelligence is changing businesses, education and everyday life.', content: 'Artificial intelligence is becoming a practical creative partner across the modern world.', image: '', icon: '🤖', author: 'Rahul Sharma', tags: ['AI', 'Innovation'], status: 'Published', date: 'Sep 16, 2026', publishDate: '2026-09-16', readTime: '6 min read', views: 1280 },
    { id: 2, title: 'How to Build Better Learning Habits', category: 'Education', description: 'Simple and practical techniques to improve focus, learning and productivity.', content: 'Better learning starts with small, repeatable habits and a curious mind.', image: '', icon: '📚', author: 'Priya Singh', tags: ['Learning', 'Focus'], status: 'Published', date: 'Sep 15, 2026', publishDate: '2026-09-15', readTime: '4 min read', views: 940 },
    { id: 3, title: 'Starting Your First Online Business', category: 'Business', description: 'Important things you should know before starting your first online business.', content: 'A focused idea, a clear audience, and consistent execution are a strong beginning.', image: '', icon: '💼', author: 'Amit Verma', tags: ['Business', 'Growth'], status: 'Published', date: 'Sep 14, 2026', publishDate: '2026-09-14', readTime: '7 min read', views: 820 },
    { id: 4, title: 'Simple Ways to Improve Your Lifestyle', category: 'Lifestyle', description: 'Small daily changes that can help you create a healthier and more productive lifestyle.', content: 'Small choices compound into a lifestyle that feels more intentional and energetic.', image: '', icon: '🌱', author: 'Neha Patel', tags: ['Wellbeing'], status: 'Published', date: 'Sep 13, 2026', publishDate: '2026-09-13', readTime: '5 min read', views: 760 },
    { id: 5, title: 'Modern Web Development Guide', category: 'Technology', description: 'Learn the fundamentals of building modern and responsive websites.', content: 'Good web experiences balance clarity, accessibility, performance, and personality.', image: '', icon: '🌐', author: 'Vikas Kumar', tags: ['Web', 'Design'], status: 'Published', date: 'Sep 12, 2026', publishDate: '2026-09-12', readTime: '8 min read', views: 690 },
    { id: 6, title: 'Productivity Tips for Professionals', category: 'Business', description: 'Useful productivity techniques for managing your work and time effectively.', content: 'Productivity is less about speed and more about protecting attention for meaningful work.', image: '', icon: '⚡', author: 'Ankit Jain', tags: ['Productivity'], status: 'Published', date: 'Sep 11, 2026', publishDate: '2026-09-11', readTime: '5 min read', views: 610 }
  ];
  const read = (key, fallback) => { try { const value = JSON.parse(localStorage.getItem(key)); return Array.isArray(value) && value.length ? value : fallback; } catch { return fallback; } };
  window.getContents = () => read(CONTENT_KEY, defaults);
  window.saveContents = items => localStorage.setItem(CONTENT_KEY, JSON.stringify(items));
  window.getCategories = () => read(CATEGORY_KEY, defaultCategories);
  window.saveCategories = items => localStorage.setItem(CATEGORY_KEY, JSON.stringify(items));
  window.addContent = item => { const items = getContents(); items.unshift(item); saveContents(items); return item; };
  window.updateContent = item => { saveContents(getContents().map(existing => existing.id === item.id ? item : existing)); return item; };
  window.deleteContent = id => saveContents(getContents().filter(item => item.id !== id));

  const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
  const imageMarkup = (item, className) => item.image ? `<img src="${escapeHtml(item.image)}" alt="${escapeHtml(item.title)}" class="${className}">` : `<span>${escapeHtml(item.icon || '✦')}</span>`;
  const published = () => getContents().filter(item => item.status === 'Published');
  const byDate = items => [...items].sort((a, b) => new Date(b.publishDate || b.date) - new Date(a.publishDate || a.date));

  function renderCategories() {
    const target = document.querySelector('.category-grid'); if (!target) return;
    const items = getCategories();
    target.innerHTML = items.map((category, index) => `<div class="category-card" onclick="filterCategory('${escapeHtml(category)}')"><div class="category-icon">${['💻','📚','📈','🌱','🩺','✈️','💰'][index % 7]}</div><h3>${escapeHtml(category)}</h3><p>${published().filter(item => item.category === category).length} Articles</p></div>`).join('');
  }
  function renderContent(items = byDate(published())) {
    const grid = document.getElementById('contentGrid'); if (!grid) return;
    grid.innerHTML = items.length ? items.map(item => `<article class="content-card" data-testid="content-card" onclick="openDetails(${item.id})"><div class="content-image">${imageMarkup(item, 'content-card-image')}</div><div class="content-info"><span>${escapeHtml(item.category)}</span><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.description)}</p><div class="content-meta"><span>${escapeHtml(item.author)}</span><span>${escapeHtml(item.readTime || '3 min read')}</span></div></div></article>`).join('') : '<div class="empty-state">No published content matches this view yet.</div>';
  }
  function renderTrending() {
    const target = document.getElementById('trendingGrid'); if (!target) return;
    target.innerHTML = [...published()].sort((a,b) => (b.views || 0) - (a.views || 0)).slice(0, 3).map((item, index) => `<div class="trending-card" onclick="openDetails(${item.id})"><strong>0${index + 1}</strong><div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.category)} · ${escapeHtml(item.readTime || '3 min read')}</p></div></div>`).join('') || '<div class="empty-state">Trending stories will appear here.</div>';
  }
  window.renderPublic = () => { renderCategories(); renderContent(); renderTrending(); const featured = byDate(published())[0]; const title = document.querySelector('.featured-content h2'); if (featured && title) { title.textContent = featured.title; const copy = document.querySelector('.featured-content p'); if (copy) copy.textContent = featured.description; const image = document.querySelector('.featured-image'); if (image) image.innerHTML = imageMarkup(featured, 'featured-card-image'); } };
  window.displayContent = renderContent;
  window.displayTrending = renderTrending;
  window.filterCategory = category => { renderContent(published().filter(item => item.category === category)); document.getElementById('latest')?.scrollIntoView({ behavior: 'smooth' }); };
  window.showAllContent = () => { renderContent(); document.getElementById('latest')?.scrollIntoView({ behavior: 'smooth' }); };
  window.openSearch = () => { document.getElementById('searchBox')?.classList.add('show'); document.getElementById('searchInput')?.focus(); };
  window.closeSearch = () => document.getElementById('searchBox')?.classList.remove('show');
  window.searchContent = () => { const term = document.getElementById('searchInput').value.toLowerCase().trim(); const box = document.getElementById('searchResults'); const results = published().filter(item => [item.title, item.description, item.category, item.author, ...(item.tags || [])].join(' ').toLowerCase().includes(term)); box.innerHTML = term ? (results.length ? results.map(item => `<div class="search-result" onclick="openDetails(${item.id});closeSearch()"><strong>${escapeHtml(item.title)}</strong><p>${escapeHtml(item.category)} · ${escapeHtml(item.author)}</p></div>`).join('') : '<p class="empty-state">No published content found.</p>') : ''; };
  window.openDetails = id => { const item = published().find(entry => entry.id === id); if (!item) return; const modal = document.getElementById('createModal'); if (!modal) return; modal.classList.remove('hidden'); modal.querySelector('.modal-box').innerHTML = `<button class="modal-close" onclick="closeCreateContent()">✕</button><div class="article-detail" data-testid="content-details"><div class="content-image">${imageMarkup(item, 'detail-image')}</div><span class="label">${escapeHtml(item.category)}</span><h2>${escapeHtml(item.title)}</h2><p class="modal-subtitle">By ${escapeHtml(item.author)} · ${escapeHtml(item.date || item.publishDate)} · ${escapeHtml(item.readTime || '3 min read')}</p><p>${escapeHtml(item.content || item.description)}</p><p class="article-tags">${(item.tags || []).map(tag => `<span>#${escapeHtml(tag)}</span>`).join(' ')}</p><button class="primary-btn" onclick="navigator.clipboard?.writeText(location.href);showToast('Link copied')">↗ Share</button></div>`; };
  window.openCreateContent = () => { const modal = document.getElementById('createModal'); if (!modal) return; modal.classList.remove('hidden'); modal.querySelector('.modal-box').innerHTML = `<button class="modal-close" onclick="closeCreateContent()">✕</button><h2>Create Content</h2><p class="modal-subtitle">Share your ideas with the community.</p><form id="contentForm"><label>Content Title</label><input data-testid="content-title" id="contentTitle" required placeholder="Enter content title"><label>Category</label><select data-testid="content-category" id="contentCategory" required><option value="">Select Category</option>${getCategories().map(category => `<option>${escapeHtml(category)}</option>`).join('')}</select><label>Author</label><input data-testid="content-author" id="contentAuthor" value="You" required><label>Tags</label><input id="contentTags" placeholder="design, ideas"><label>Cover Image URL</label><input id="contentImage" type="url" placeholder="https://..."><label>Short Description</label><input id="contentShortDescription" required placeholder="A concise summary"><label>Full Content</label><textarea id="contentDescription" rows="6" required placeholder="Write your content..."></textarea><label>Status</label><select data-testid="content-status" id="contentStatus"><option>Published</option><option>Draft</option></select><button data-testid="save-content" class="primary-btn full-btn" type="submit">Save Content</button></form>`; modal.querySelector('#contentForm').addEventListener('submit', event => { event.preventDefault(); const title = document.getElementById('contentTitle').value.trim(); const description = document.getElementById('contentShortDescription').value.trim(); const item = { id: Date.now(), title, category: document.getElementById('contentCategory').value, author: document.getElementById('contentAuthor').value.trim(), tags: document.getElementById('contentTags').value.split(',').map(tag => tag.trim()).filter(Boolean), image: document.getElementById('contentImage').value.trim(), description, content: document.getElementById('contentDescription').value.trim(), status: document.getElementById('contentStatus').value, date: new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }), publishDate: new Date().toISOString().slice(0,10), readTime: '3 min read', views: 0, icon: '✦' }; addContent(item); closeCreateContent(); renderPublic(); showToast(item.status === 'Published' ? 'Content published' : 'Draft saved'); }); };
  window.closeCreateContent = () => document.getElementById('createModal')?.classList.add('hidden');
  window.scrollToLatest = () => document.getElementById('latest')?.scrollIntoView({ behavior: 'smooth' });
  window.showToast = message => { const toast = document.createElement('div'); toast.className = 'toast'; toast.textContent = message; document.body.appendChild(toast); setTimeout(() => toast.remove(), 2600); };

  document.addEventListener('DOMContentLoaded', () => { const form = document.getElementById('contentForm'); if (form) form.replaceWith(form.cloneNode(true)); renderPublic(); const match = location.hash.match(/^#content-(\d+)$/); if (match) setTimeout(() => openDetails(Number(match[1])), 0); });
  window.addEventListener('storage', renderPublic);
})();
