(() => {
  window.__contentHubWebStoriesLoaded = true;
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[char]));
  const storyImage = (story, slide) => { const source = slide?.image || story.coverImage; return source ? `<img class="story-cover" src="${esc(source)}" alt="${esc(slide?.title || story.title)}">` : `<div class="story-cover-fallback">${esc(story.icon || '✦')}</div>`; };
  const publishedStories = () => getWebStories().filter(story => story.status === 'Published');
  const storyCard = story => { const seconds = (story.slides || []).reduce((sum, slide) => sum + Number(slide.duration || 5), 0); const duration = seconds < 60 ? `${seconds}s` : `${Math.ceil(seconds / 60)} min`; return `<a class="story-card" data-testid="web-story-card" href="web-story-details.html?id=${encodeURIComponent(story.id)}">${story.featured ? '<span class="story-badge">Featured</span>' : ''}<span class="story-duration">${(story.slides || []).length} slides</span>${storyImage(story)}<div class="story-card-body"><span class="eyebrow">${esc(story.category)}</span><h2>${esc(story.title)}</h2><p>${esc(story.author)} · ${duration}</p></div></a>`; };
  function renderStoryPage() { const grid = document.querySelector('#storyGrid'); if (!grid) return; const query = document.querySelector('#webStorySearch')?.value.toLowerCase().trim() || ''; const category = document.querySelector('#webStoryCategory')?.value || ''; const featured = document.querySelector('#webStoryFeatured')?.value || ''; const stories = publishedStories().filter(story => (!query || [story.title, story.category, story.author].join(' ').toLowerCase().includes(query)) && (!category || story.category === category) && (!featured || String(story.featured) === featured)); grid.innerHTML = stories.length ? stories.map(storyCard).join('') : '<div class="story-empty">No published Web Stories match these filters.</div>'; }
  function initStoryPage() { const grid = document.querySelector('#storyGrid'); if (!grid) return; const category = document.querySelector('#webStoryCategory'); category.innerHTML = '<option value="">All categories</option>' + getCategories().map(item => `<option>${esc(item)}</option>`).join(''); ['webStorySearch','webStoryCategory','webStoryFeatured'].forEach(id => document.getElementById(id)?.addEventListener('input', renderStoryPage)); renderStoryPage(); }
  function addStoryNavigation() { document.querySelectorAll('.nav-links').forEach(nav => { if (!nav.querySelector('a[href="web-stories.html"]')) { const link = document.createElement('a'); link.href = 'web-stories.html'; link.textContent = 'Web Stories'; nav.insertBefore(link, nav.querySelector('a[href="about.html"]') || null); } }); }
  function renderHomeStories() { let target = document.querySelector('#homeWebStories'); if (!target && location.pathname.endsWith('index.html')) { const newsletter = document.querySelector('.newsletter'); if (newsletter) { const section = document.createElement('section'); section.className = 'section'; section.innerHTML = '<div class="container"><div class="section-head"><div><span class="eyebrow">Quick visual ideas</span><h2>Web Stories</h2></div><a class="read-more" href="web-stories.html">View All Stories →</a></div><div id="homeWebStories" class="story-grid"></div></div>'; newsletter.parentNode.insertBefore(section, newsletter); target = section.querySelector('#homeWebStories'); } } if (!target) return; const stories = publishedStories().filter(story => story.featured).slice(0, 4); target.innerHTML = stories.length ? stories.map(storyCard).join('') : '<div class="story-empty">Featured Web Stories will appear here.</div>'; }
  function initViewer() { const viewer = document.querySelector('#storyViewer'); if (!viewer) return; const story = getWebStoryById(new URLSearchParams(location.search).get('id')); if (!story || story.status !== 'Published') { viewer.innerHTML = '<div class="story-empty">This Web Story is unavailable.</div>'; return; } const slides = story.slides?.length ? story.slides : [{ image: story.coverImage, title: story.title, description: story.description, duration: 5 }]; let index = 0; let playing = true; let timer; const progress = viewer.querySelector('#storyProgress'); const image = viewer.querySelector('#storyImage'); image.setAttribute('data-testid', 'story-slide'); const label = viewer.querySelector('#storyLabel'); const title = viewer.querySelector('#storyTitle'); const description = viewer.querySelector('#storyDescription'); const author = viewer.querySelector('#storyAuthor'); const playButton = viewer.querySelector('#storyPlay');
    function render() { const slide = slides[index]; image.innerHTML = storyImage(story, slide); label.textContent = story.category; title.textContent = slide.title || story.title; description.textContent = slide.description || story.description; author.textContent = `${story.author} · Slide ${index + 1} of ${slides.length}`; progress.innerHTML = slides.map((_, position) => `<span class="story-progress-segment ${position < index ? 'complete' : position === index ? 'current' : ''}"><i class="story-progress-fill"></i></span>`).join(''); const segment = progress.children[index]; if (segment) segment.querySelector('.story-progress-fill').style.animationDuration = `${Number(slide.duration || 5)}s`; playButton.textContent = playing ? 'Ⅱ' : '▶'; }
    function stopTimer() { clearTimeout(timer); }
    function schedule() { stopTimer(); if (playing && index < slides.length - 1) timer = setTimeout(() => { index += 1; render(); schedule(); }, Number(slides[index].duration || 5) * 1000); }
    function move(step) { index = Math.min(Math.max(index + step, 0), slides.length - 1); if (index === slides.length - 1 && step > 0) playing = false; render(); schedule(); }
    viewer.querySelector('#storyNext').addEventListener('click', () => move(1)); viewer.querySelector('#storyPrevious').addEventListener('click', () => move(-1)); viewer.querySelector('#storyPlay').addEventListener('click', () => { playing = true; render(); schedule(); }); viewer.querySelector('#storyPause').addEventListener('click', () => { playing = false; stopTimer(); render(); }); viewer.querySelector('#storyClose').addEventListener('click', () => { location.href = 'web-stories.html'; }); viewer.querySelector('#storyShare').addEventListener('click', async () => { try { await navigator.clipboard.writeText(location.href); window.showToast?.('Story link copied'); } catch { window.showToast?.('Copy the URL from your browser'); } }); viewer.querySelector('.story-tap-zone.left').addEventListener('click', () => move(-1)); viewer.querySelector('.story-tap-zone.right').addEventListener('click', () => move(1)); render(); schedule();
  }
  const boot = () => { addStoryNavigation(); initStoryPage(); renderHomeStories(); initViewer(); }; if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot); else boot(); window.addEventListener('storage', () => { initStoryPage(); renderHomeStories(); });
})();
